services:
  fate:
    build:
      context: .
      dockerfile: Dockerfile
    image: fate:latest
    container_name: fate
    restart: unless-stopped
    ports:
      - '8080:80'
    networks:
      - proxy_network
    labels:
      - 'com.docker.compose.project=fate'

networks:
  proxy_network:
    external: true
